# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CodeBlock.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CodeBlock.proto',
  package='gtirb.proto',
  syntax='proto3',
  serialized_options=_b('\n\032com.grammatech.gtirb.proto'),
  serialized_pb=_b('\n\x0f\x43odeBlock.proto\x12\x0bgtirb.proto\"d\n\tCodeBlock\x12\x0c\n\x04uuid\x18\x01 \x01(\x0c\x12\x0c\n\x04size\x18\x03 \x01(\x04\x12,\n\x0b\x64\x65\x63ode_mode\x18\x04 \x01(\x0e\x32\x17.gtirb.proto.DecodeModeJ\x04\x08\x02\x10\x03R\x07\x61\x64\x64ress*,\n\nDecodeMode\x12\x0f\n\x0b\x41ll_Default\x10\x00\x12\r\n\tARM_Thumb\x10\x01\x42\x1c\n\x1a\x63om.grammatech.gtirb.protob\x06proto3')
)

_DECODEMODE = _descriptor.EnumDescriptor(
  name='DecodeMode',
  full_name='gtirb.proto.DecodeMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='All_Default', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARM_Thumb', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=134,
  serialized_end=178,
)
_sym_db.RegisterEnumDescriptor(_DECODEMODE)

DecodeMode = enum_type_wrapper.EnumTypeWrapper(_DECODEMODE)
All_Default = 0
ARM_Thumb = 1



_CODEBLOCK = _descriptor.Descriptor(
  name='CodeBlock',
  full_name='gtirb.proto.CodeBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='gtirb.proto.CodeBlock.uuid', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='gtirb.proto.CodeBlock.size', index=1,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decode_mode', full_name='gtirb.proto.CodeBlock.decode_mode', index=2,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=132,
)

_CODEBLOCK.fields_by_name['decode_mode'].enum_type = _DECODEMODE
DESCRIPTOR.message_types_by_name['CodeBlock'] = _CODEBLOCK
DESCRIPTOR.enum_types_by_name['DecodeMode'] = _DECODEMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CodeBlock = _reflection.GeneratedProtocolMessageType('CodeBlock', (_message.Message,), dict(
  DESCRIPTOR = _CODEBLOCK,
  __module__ = 'CodeBlock_pb2'
  # @@protoc_insertion_point(class_scope:gtirb.proto.CodeBlock)
  ))
_sym_db.RegisterMessage(CodeBlock)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
