# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataBlock.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DataBlock.proto',
  package='gtirb.proto',
  syntax='proto3',
  serialized_options=_b('\n\032com.grammatech.gtirb.proto'),
  serialized_pb=_b('\n\x0f\x44\x61taBlock.proto\x12\x0bgtirb.proto\"6\n\tDataBlock\x12\x0c\n\x04uuid\x18\x01 \x01(\x0c\x12\x0c\n\x04size\x18\x03 \x01(\x04J\x04\x08\x02\x10\x03R\x07\x61\x64\x64ressB\x1c\n\x1a\x63om.grammatech.gtirb.protob\x06proto3')
)




_DATABLOCK = _descriptor.Descriptor(
  name='DataBlock',
  full_name='gtirb.proto.DataBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='gtirb.proto.DataBlock.uuid', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='gtirb.proto.DataBlock.size', index=1,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['DataBlock'] = _DATABLOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataBlock = _reflection.GeneratedProtocolMessageType('DataBlock', (_message.Message,), dict(
  DESCRIPTOR = _DATABLOCK,
  __module__ = 'DataBlock_pb2'
  # @@protoc_insertion_point(class_scope:gtirb.proto.DataBlock)
  ))
_sym_db.RegisterMessage(DataBlock)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
