# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProxyBlock.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProxyBlock.proto',
  package='gtirb.proto',
  syntax='proto3',
  serialized_options=_b('\n\032com.grammatech.gtirb.proto'),
  serialized_pb=_b('\n\x10ProxyBlock.proto\x12\x0bgtirb.proto\"\x1a\n\nProxyBlock\x12\x0c\n\x04uuid\x18\x01 \x01(\x0c\x42\x1c\n\x1a\x63om.grammatech.gtirb.protob\x06proto3')
)




_PROXYBLOCK = _descriptor.Descriptor(
  name='ProxyBlock',
  full_name='gtirb.proto.ProxyBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='gtirb.proto.ProxyBlock.uuid', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['ProxyBlock'] = _PROXYBLOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProxyBlock = _reflection.GeneratedProtocolMessageType('ProxyBlock', (_message.Message,), dict(
  DESCRIPTOR = _PROXYBLOCK,
  __module__ = 'ProxyBlock_pb2'
  # @@protoc_insertion_point(class_scope:gtirb.proto.ProxyBlock)
  ))
_sym_db.RegisterMessage(ProxyBlock)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
