# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SymbolicExpression.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SymbolicExpression.proto',
  package='gtirb.proto',
  syntax='proto3',
  serialized_options=_b('\n\032com.grammatech.gtirb.proto'),
  serialized_pb=_b('\n\x18SymbolicExpression.proto\x12\x0bgtirb.proto\"4\n\rSymStackConst\x12\x0e\n\x06offset\x18\x01 \x01(\x05\x12\x13\n\x0bsymbol_uuid\x18\x02 \x01(\x0c\"3\n\x0cSymAddrConst\x12\x0e\n\x06offset\x18\x01 \x01(\x03\x12\x13\n\x0bsymbol_uuid\x18\x02 \x01(\x0c\"X\n\x0bSymAddrAddr\x12\r\n\x05scale\x18\x01 \x01(\x03\x12\x0e\n\x06offset\x18\x02 \x01(\x03\x12\x14\n\x0csymbol1_uuid\x18\x03 \x01(\x0c\x12\x14\n\x0csymbol2_uuid\x18\x04 \x01(\x0c\"\xc7\x01\n\x12SymbolicExpression\x12/\n\naddr_const\x18\x02 \x01(\x0b\x32\x19.gtirb.proto.SymAddrConstH\x00\x12-\n\taddr_addr\x18\x03 \x01(\x0b\x32\x18.gtirb.proto.SymAddrAddrH\x00\x12\x35\n\x0f\x61ttribute_flags\x18\x04 \x03(\x0e\x32\x1c.gtirb.proto.SEAttributeFlagB\x07\n\x05valueJ\x04\x08\x01\x10\x02R\x0bstack_const*\xc7\x02\n\x0fSEAttributeFlag\x12\t\n\x05Part0\x10\x00\x12\t\n\x05Part1\x10\x01\x12\t\n\x05Part2\x10\x02\x12\t\n\x05Part3\x10\x03\x12\x0c\n\x08\x41\x64justed\x10\x04\x12\n\n\x06GotRef\x10\x05\x12\x0c\n\x08GotRelPC\x10\x06\x12\r\n\tGotRelGot\x10\x07\x12\x0e\n\nAddrRelGot\x10\x08\x12\x0e\n\nGotRelAddr\x10\t\x12\x0b\n\x07GotPage\x10\n\x12\x0f\n\x0bGotPageOfst\x10\x0b\x12\n\n\x06PltRef\x10\x0c\x12\n\n\x06GotOff\x10\r\x12\t\n\x05TpOff\x10\x0e\x12\n\n\x06NtpOff\x10\x0f\x12\n\n\x06\x44tpOff\x10\x10\x12\t\n\x05TlsGd\x10\x11\x12\t\n\x05TlsLd\x10\x12\x12\x06\n\x02Lo\x10\x13\x12\x06\n\x02Hi\x10\x14\x12\x08\n\x04Lo12\x10\x15\x12\x07\n\x03\x41\x62s\x10\x16\x12\n\n\x06Signed\x10\x17\x12\x13\n\x0fNoOverflowCheck\x10\x18\x42\x1c\n\x1a\x63om.grammatech.gtirb.protob\x06proto3')
)

_SEATTRIBUTEFLAG = _descriptor.EnumDescriptor(
  name='SEAttributeFlag',
  full_name='gtirb.proto.SEAttributeFlag',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Part0', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Part1', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Part2', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Part3', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Adjusted', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GotRef', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GotRelPC', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GotRelGot', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AddrRelGot', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GotRelAddr', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GotPage', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GotPageOfst', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PltRef', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GotOff', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TpOff', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NtpOff', index=15, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DtpOff', index=16, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TlsGd', index=17, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TlsLd', index=18, number=18,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Lo', index=19, number=19,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Hi', index=20, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Lo12', index=21, number=21,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Abs', index=22, number=22,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Signed', index=23, number=23,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NoOverflowCheck', index=24, number=24,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=441,
  serialized_end=768,
)
_sym_db.RegisterEnumDescriptor(_SEATTRIBUTEFLAG)

SEAttributeFlag = enum_type_wrapper.EnumTypeWrapper(_SEATTRIBUTEFLAG)
Part0 = 0
Part1 = 1
Part2 = 2
Part3 = 3
Adjusted = 4
GotRef = 5
GotRelPC = 6
GotRelGot = 7
AddrRelGot = 8
GotRelAddr = 9
GotPage = 10
GotPageOfst = 11
PltRef = 12
GotOff = 13
TpOff = 14
NtpOff = 15
DtpOff = 16
TlsGd = 17
TlsLd = 18
Lo = 19
Hi = 20
Lo12 = 21
Abs = 22
Signed = 23
NoOverflowCheck = 24



_SYMSTACKCONST = _descriptor.Descriptor(
  name='SymStackConst',
  full_name='gtirb.proto.SymStackConst',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='gtirb.proto.SymStackConst.offset', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol_uuid', full_name='gtirb.proto.SymStackConst.symbol_uuid', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=93,
)


_SYMADDRCONST = _descriptor.Descriptor(
  name='SymAddrConst',
  full_name='gtirb.proto.SymAddrConst',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='gtirb.proto.SymAddrConst.offset', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol_uuid', full_name='gtirb.proto.SymAddrConst.symbol_uuid', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=146,
)


_SYMADDRADDR = _descriptor.Descriptor(
  name='SymAddrAddr',
  full_name='gtirb.proto.SymAddrAddr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scale', full_name='gtirb.proto.SymAddrAddr.scale', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='gtirb.proto.SymAddrAddr.offset', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol1_uuid', full_name='gtirb.proto.SymAddrAddr.symbol1_uuid', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol2_uuid', full_name='gtirb.proto.SymAddrAddr.symbol2_uuid', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=236,
)


_SYMBOLICEXPRESSION = _descriptor.Descriptor(
  name='SymbolicExpression',
  full_name='gtirb.proto.SymbolicExpression',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addr_const', full_name='gtirb.proto.SymbolicExpression.addr_const', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addr_addr', full_name='gtirb.proto.SymbolicExpression.addr_addr', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attribute_flags', full_name='gtirb.proto.SymbolicExpression.attribute_flags', index=2,
      number=4, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='gtirb.proto.SymbolicExpression.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=239,
  serialized_end=438,
)

_SYMBOLICEXPRESSION.fields_by_name['addr_const'].message_type = _SYMADDRCONST
_SYMBOLICEXPRESSION.fields_by_name['addr_addr'].message_type = _SYMADDRADDR
_SYMBOLICEXPRESSION.fields_by_name['attribute_flags'].enum_type = _SEATTRIBUTEFLAG
_SYMBOLICEXPRESSION.oneofs_by_name['value'].fields.append(
  _SYMBOLICEXPRESSION.fields_by_name['addr_const'])
_SYMBOLICEXPRESSION.fields_by_name['addr_const'].containing_oneof = _SYMBOLICEXPRESSION.oneofs_by_name['value']
_SYMBOLICEXPRESSION.oneofs_by_name['value'].fields.append(
  _SYMBOLICEXPRESSION.fields_by_name['addr_addr'])
_SYMBOLICEXPRESSION.fields_by_name['addr_addr'].containing_oneof = _SYMBOLICEXPRESSION.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['SymStackConst'] = _SYMSTACKCONST
DESCRIPTOR.message_types_by_name['SymAddrConst'] = _SYMADDRCONST
DESCRIPTOR.message_types_by_name['SymAddrAddr'] = _SYMADDRADDR
DESCRIPTOR.message_types_by_name['SymbolicExpression'] = _SYMBOLICEXPRESSION
DESCRIPTOR.enum_types_by_name['SEAttributeFlag'] = _SEATTRIBUTEFLAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SymStackConst = _reflection.GeneratedProtocolMessageType('SymStackConst', (_message.Message,), dict(
  DESCRIPTOR = _SYMSTACKCONST,
  __module__ = 'SymbolicExpression_pb2'
  # @@protoc_insertion_point(class_scope:gtirb.proto.SymStackConst)
  ))
_sym_db.RegisterMessage(SymStackConst)

SymAddrConst = _reflection.GeneratedProtocolMessageType('SymAddrConst', (_message.Message,), dict(
  DESCRIPTOR = _SYMADDRCONST,
  __module__ = 'SymbolicExpression_pb2'
  # @@protoc_insertion_point(class_scope:gtirb.proto.SymAddrConst)
  ))
_sym_db.RegisterMessage(SymAddrConst)

SymAddrAddr = _reflection.GeneratedProtocolMessageType('SymAddrAddr', (_message.Message,), dict(
  DESCRIPTOR = _SYMADDRADDR,
  __module__ = 'SymbolicExpression_pb2'
  # @@protoc_insertion_point(class_scope:gtirb.proto.SymAddrAddr)
  ))
_sym_db.RegisterMessage(SymAddrAddr)

SymbolicExpression = _reflection.GeneratedProtocolMessageType('SymbolicExpression', (_message.Message,), dict(
  DESCRIPTOR = _SYMBOLICEXPRESSION,
  __module__ = 'SymbolicExpression_pb2'
  # @@protoc_insertion_point(class_scope:gtirb.proto.SymbolicExpression)
  ))
_sym_db.RegisterMessage(SymbolicExpression)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
